# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["usbhid"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  # 根在 SD 卡的 f2fs 上(2026-08-15 从 eMMC 搬过来)。选 f2fs 是因为这张卡上报
  # DISC-GRAN = 4M,log-structured 的顺序写正对这个擦除块尺寸。
  #
  # **eMMC 上的 ext4 根原封不动留着**(UUID 91dd2c0a-…),是回退目标。
  # 迁移的理由、实测数据、以及恢复方法见 docs/runbooks/r6s.md。
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/99e8c9ba-539f-45a2-8b80-aecebef9a1af";
    fsType = "f2fs";
    options = ["noatime"];
  };

  # ESP 继续留在 eMMC 上。U-Boot/UEFI 只认它,内核和 initrd 都从这里读,
  # 所以引导器全程不需要认识 f2fs —— 卡上只有根。
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/36F4-144D";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
