# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # r8169 = enp5s0，initrd 里的救援 sshd 要用它上网，别删。
  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "ehci_pci" "usbhid" "uas" "sd_mod" "r8169"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.kernelParams = ["mitigations=off" "libata.force=3.00:disable"];

  # 根在 sdc(ssd.fast) + sda(hdd.14t) 组成的 bcachefs 上。必须写 UUID= 形式：
  # mount.bcachefs 会用它扫描出所有成员设备，写 /dev/sdX 会在盘符漂移时挂不上。
  fileSystems."/" = {
    device = "UUID=2dc8bfeb-1f02-4c70-94dc-ecd07593e7f1";
    fsType = "bcachefs";
    options = ["noatime"];
  };

  # sdd1，唯一还留在旧系统盘上的东西。systemd-boot 直接把内核放这里，
  # 引导器就不需要会读 bcachefs（GRUB 不会，所以从 GRUB 换掉了）。
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/59E1-040D";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
