# SPDX-License-Identifier: GPL-2.0

gunyah-y += rsc_mgr_legacy.o rsc_mgr_rpc.o vm_mgr.o vm_mgr_mm.o gunyah_hypercall.o
obj-$(CONFIG_GUNYAH) += gunyah.o

obj-$(CONFIG_GUNYAH_VCPU) += gunyah_vcpu.o
obj-$(CONFIG_GUNYAH_IRQFD) += gunyah_irqfd.o
obj-$(CONFIG_GUNYAH_IOEVENTFD) += gunyah_ioeventfd.o
