theme = catppuccin-macchiato

keybind = shift+ctrl+r=reload_config

keybind = "cmd+t=new_tab"

keybind = "cmd+w=close_surface"

keybind = shift+ctrl+h=new_split:left
keybind = shift+ctrl+l=new_split:right
keybind = shift+ctrl+j=new_split:up
keybind = shift+ctrl+k=new_split:down

font-family = FiraCode Nerd Font
font-feature = "+liga", "+calt"

background-opacity = 0.9

macos-titlebar-style = "transparent"

window-padding-x = 10

window-padding-y = 10
